### PR TITLE
Prepare 0.6.4

### PR DESCRIPTION
**Pull request by ekohl**
Turns out the CHANGELOG was not up to date. This fixes it.

### CODE REVIEW

**Comment by bastelfreak** [comment]
@ekohl what happend to the Gemfile so it fails now? :(

**Comment by ekohl** [comment]
@bastelfreak it looks like ```Gemfile.lock``` is not in .gitignore. Going to nuke it.

**Comment by ekohl** [comment]
Ok, so the Gemfile.lock for now is somewhat useful until we migrate the specs.

**Comment by ekohl** [comment]
💚

**Pull request merged**
