### PR TITLE
Prepare for release 0.6.0

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by bastelfreak** [comment]
@ekohl do we need to adjust author/email in the librarian.gemspec file? Are we even allowed to change it?

----

I tried to cleanup the testmatrix in https://github.com/voxpupuli/librarian/pull/6

**Comment by ekohl** [comment]
@bastelfreak no idea about the author. Right now I'd like to get a release out of the door so it works again with Git 2.14.0 since that's what Travis has installed.

**Comment by bastelfreak** [comment]
I am fine with leaving it as is. Can you take a look at PR #6 ?

**Comment by ekohl** [comment]
Anything I can do to move this along?

**Comment by ekohl** [comment]
Rebased

**Pull request merged**
